export const COUNTRIES = [
  { code: "TR", name: "Türkiye", dial: "+90", flag: "🇹🇷" },
  { code: "DE", name: "Almanya", dial: "+49", flag: "🇩🇪" },
  { code: "US", name: "Amerika", dial: "+1", flag: "🇺🇸" },
  { code: "AU", name: "Avustralya", dial: "+61", flag: "🇦🇺" },
  { code: "AT", name: "Avusturya", dial: "+43", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaycan", dial: "+994", flag: "🇦🇿" },
  { code: "BE", name: "Belçika", dial: "+32", flag: "🇧🇪" },
  { code: "GB", name: "Birleşik Krallık", dial: "+44", flag: "🇬🇧" },
  { code: "BG", name: "Bulgaristan", dial: "+359", flag: "🇧🇬" },
  { code: "DK", name: "Danimarka", dial: "+45", flag: "🇩🇰" },
  { code: "FI", name: "Finlandiya", dial: "+358", flag: "🇫🇮" },
  { code: "FR", name: "Fransa", dial: "+33", flag: "🇫🇷" },
  { code: "GE", name: "Gürcistan", dial: "+995", flag: "🇬🇪" },
  { code: "NL", name: "Hollanda", dial: "+31", flag: "🇳🇱" },
  { code: "IE", name: "İrlanda", dial: "+353", flag: "🇮🇪" },
  { code: "ES", name: "İspanya", dial: "+34", flag: "🇪🇸" },
  { code: "SE", name: "İsveç", dial: "+46", flag: "🇸🇪" },
  { code: "CH", name: "İsviçre", dial: "+41", flag: "🇨🇭" },
  { code: "IT", name: "İtalya", dial: "+39", flag: "🇮🇹" },
  { code: "CA", name: "Kanada", dial: "+1", flag: "🇨🇦" },
  { code: "CY", name: "Kıbrıs", dial: "+357", flag: "🇨🇾" },
  { code: "HR", name: "Hırvatistan", dial: "+385", flag: "🇭🇷" },
  { code: "LB", name: "Lübnan", dial: "+961", flag: "🇱🇧" },
  { code: "HU", name: "Macaristan", dial: "+36", flag: "🇭🇺" },
  { code: "NO", name: "Norveç", dial: "+47", flag: "🇳🇴" },
  { code: "PL", name: "Polonya", dial: "+48", flag: "🇵🇱" },
  { code: "PT", name: "Portekiz", dial: "+351", flag: "🇵🇹" },
  { code: "RO", name: "Romanya", dial: "+40", flag: "🇷🇴" },
  { code: "RU", name: "Rusya", dial: "+7", flag: "🇷🇺" },
  { code: "RS", name: "Sırbistan", dial: "+381", flag: "🇷🇸" },
  { code: "GR", name: "Yunanistan", dial: "+30", flag: "🇬🇷" },
] as const;

export type Country = (typeof COUNTRIES)[number];
